status-page/statuspage/statuspage/urls.py
from django.conf import settings
from django.views.static import serve

from extras.plugins.urls import plugin_patterns, plugin_api_patterns, plugin_admin_patterns
from .admin import admin_site
from django.urls import path, include, re_path
from statuspage.views import HomeView, DashboardHomeView, SubscriberVerifyView, SubscriberManageView, \
    SubscriberUnsubscribeView, SubscriberSubscribeView, SubscriberRequestManagementKeyView, \
    SubscriberManageWebhookListView, SubscriberManageWebhookCreateView, SubscriberManageWebhookDeleteView, \
    SubscriberManageWebhookEditView
from users.views import LoginView, LogoutView
from statuspage.api.views import APIRootView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

openapi_info = openapi.Info(
    title="Status-Page API",
    default_version='v1',
    description="API to access Status-Page",
    terms_of_service="https://github.com/status-page/status-page",
    license=openapi.License(name="Apache 2.0 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=()
)

_patterns = [
    # Base Views
    path('', HomeView.as_view(), name='home'),

    path('subscribers/subscribe', SubscriberSubscribeView.as_view(), name='subscriber_subscribe'),
    path('subscribers/reqeust-management-key', SubscriberRequestManagementKeyView.as_view(), name='subscriber_management_key'),
    path('subscribers/<str:management_key>/verify', SubscriberVerifyView.as_view(), name='subscriber_verify'),
    path('subscribers/<str:management_key>/manage', SubscriberManageView.as_view(), name='subscriber_manage'),
    path('subscribers/<str:management_key>/manage/webhooks', SubscriberManageWebhookListView.as_view(), name='subscriber_manage_webhook_list'),
    path('subscribers/<str:management_key>/manage/webhooks/create', SubscriberManageWebhookCreateView.as_view(), name='subscriber_manage_webhook_create'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/edit', SubscriberManageWebhookEditView.as_view(), name='subscriber_manage_webhook_edit'),
    path('subscribers/<str:management_key>/manage/webhooks/<int:webhook>/delete', SubscriberManageWebhookDeleteView.as_view(), name='subscriber_manage_webhook_delete'),
    path('subscribers/<str:management_key>/unsubscribe', SubscriberUnsubscribeView.as_view(), name='subscriber_unsubscribe'),

    path('dashboard/', DashboardHomeView.as_view(), name='dashboard'),
    path('dashboard/login/', LoginView.as_view(), name='login'),
    path('dashboard/logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('dashboard/components/', include('components.urls')),
    path('dashboard/extras/', include('extras.urls')),
    path('dashboard/incidents/', include('incidents.urls')),
    path('dashboard/maintenances/', include('maintenances.urls')),
    path('dashboard/metrics/', include('metrics.urls')),
    path('dashboard/subscribers/', include('subscribers.urls')),
    path('dashboard/user/', include('users.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/components/', include('components.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/incidents/', include('incidents.api.urls')),
    path('api/maintenances/', include('maintenances.api.urls')),
    path('api/metrics/', include('metrics.api.urls')),
    path('api/subscribers/', include('subscribers.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=86400), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=86400), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=86400),
            name='schema_swagger'),

    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),

    path('__reload__/', include('django_browser_reload.urls')),
]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

status-page/statuspage/users/urls.py
from django.urls import path, include

from utilities.urls import get_model_urls
from . import views

app_name = 'users'
urlpatterns = [
    # User
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),

    # API Tokens
    path('api-tokens/', include(get_model_urls('users', 'token'))),

    # Two-Factor devices
    path('twofactor/', views.TwoFactorListView.as_view(), name='device_list'),
    path('twofactor/add/', views.TwoFactorEditView.as_view(), name='device_add'),
    path('twofactor/<int:pk>/backup-codes/', views.TwoFactorBackupCodesListView.as_view(), name='device_backup_codes'),
    path('twofactor/<int:pk>/qr-code/', views.TwoFactorQRCodeListView.as_view(), name='device_qr_code'),
    path('twofactor/<int:pk>/edit/', views.TwoFactorEditView.as_view(), name='device_edit'),
    path('twofactor/<int:pk>/delete/', views.TwoFactorDeleteView.as_view(), name='device_delete'),
]

status-page/statuspage/statuspage/forms/base.py
from django import forms
from django.contrib.contenttypes.models import ContentType

from utilities.forms import TailwindMixin

__all__ = (
    'StatusPageModelForm',
    'StatusPageModelBulkEditForm',
)


class StatusPageModelForm(TailwindMixin, forms.ModelForm):
    """
    Base form for creating & editing StatusPage models. Extends Django's ModelForm to add support for custom fields.
    Attributes:
        fieldsets: An iterable of two-tuples which define a heading and field set to display per section of
            the rendered form (optional). If not defined, the all fields will be rendered as a single section.
    """
    fieldsets = ()

    def _get_content_type(self):
        return ContentType.objects.get_for_model(self._meta.model)

    def _get_form_field(self, customfield):
        if self.instance.pk:
            form_field = customfield.to_form_field(set_initial=False)
            form_field.initial = self.instance.custom_field_data.get(customfield.name, None)
            return form_field

        return customfield.to_form_field()

    def clean(self):
        return super().clean()


class StatusPageModelBulkEditForm(TailwindMixin, forms.Form):
    """
    Base form for modifying multiple StatusPage objects (of the same type) in bulk via the UI. Adds support for custom
    fields and adding/removing tags.
    Attributes:
        fieldsets: An iterable of two-tuples which define a heading and field set to display per section of
            the rendered form (optional). If not defined, the all fields will be rendered as a single section.
        nullable_fields: A list of field names indicating which fields support being set to null/empty
    """
    nullable_fields = ()

    pk = forms.ModelMultipleChoiceField(
        queryset=None,  # Set from self.model on init
        widget=forms.MultipleHiddenInput
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['pk'].queryset = self.model.objects.all()

    def _get_form_field(self, customfield):
        return customfield.to_form_field(set_initial=False, enforce_required=False)

status-page/statuspage/statuspage/views/dashboard.py
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone

from incidents.choices import IncidentStatusChoices
from incidents.models import Incident
from maintenances.choices import MaintenanceStatusChoices
from maintenances.models import Maintenance
from statuspage.views import BaseView


__all__ = (
    'DashboardHomeView',
)


class DashboardHomeView(BaseView):
    template_name = 'dashboard/home.html'

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect("login")

        open_incidents = Incident.objects.filter(
            ~Q(status=IncidentStatusChoices.RESOLVED)
        )
        open_maintenances = Maintenance.objects.filter(
            ~Q(status=MaintenanceStatusChoices.COMPLETED)
        )
        upcoming_maintenances = Maintenance.objects.filter(
            ~Q(status=MaintenanceStatusChoices.COMPLETED),
            scheduled_at__gte=timezone.now(),
        )

        return render(request, self.template_name, {
            'open_incidents': len(open_incidents),
            'open_maintenances': len(open_maintenances),
            'upcoming_maintenances': len(upcoming_maintenances),
        })

status-page/statuspage/statuspage/views/home.py
from itertools import chain

from django.db.models import Prefetch, Q
from django.shortcuts import render
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from components.choices import ComponentStatusChoices
from components.models import ComponentGroup, Component
from incidents.choices import IncidentStatusChoices
from incidents.models import Incident
from maintenances.choices import MaintenanceStatusChoices
from maintenances.models import Maintenance
from metrics.models import Metric
from statuspage.config import get_config
from statuspage.views import BaseView


__all__ = (
    'HomeView',
)


class HomeView(BaseView):
    template_name = 'home.html'

    def get(self, request):
        config = get_config()
        component_groups = ComponentGroup.objects.filter(visibility=True)\
            .prefetch_related(Prefetch('components', queryset=Component.objects.filter(visibility=True)),
                              Prefetch('components__incidents', queryset=Incident.objects.filter(visibility=True)))
        ungrouped_components = Component.objects.filter(component_group=None, visibility=True)\
            .prefetch_related(Prefetch('incidents', queryset=Incident.objects.filter(visibility=True)))

        open_incidents = Incident.objects.filter(
            ~Q(status=IncidentStatusChoices.RESOLVED),
            visibility=True,
        )
        open_maintenances = Maintenance.objects.filter(
            ~Q(status=MaintenanceStatusChoices.SCHEDULED),
            ~Q(status=MaintenanceStatusChoices.COMPLETED),
            visibility=True,
        )
        open_incidents_maintenances = list(chain(open_incidents, open_maintenances))

        upcoming_maintenances = Maintenance.objects.filter(
            status=MaintenanceStatusChoices.SCHEDULED,
            visibility=True,
        )

        datenow = timezone.now().replace(microsecond=0, second=0, minute=0, hour=0)
        datenow_end = timezone.now().replace(microsecond=0, second=59, minute=59, hour=23)
        daterange = datenow - timezone.timedelta(days=7)

        resolved_incidents = Incident.objects.filter(
            status=IncidentStatusChoices.RESOLVED,
            visibility=True,
            last_updated__range=(daterange, datenow_end),
        )
        resolved_maintenances = Maintenance.objects.filter(
            status=MaintenanceStatusChoices.COMPLETED,
            visibility=True,
            last_updated__range=(daterange, datenow_end),
        )

        resolved_incidents_maintenances = []

        date_begin = list(datenow - timezone.timedelta(days=n) for n in range(7))
        date_end = list(datenow_end - timezone.timedelta(days=n) for n in range(7))
        for count in range(7):
            local_list = []
            begin = date_begin[count]
            end = date_end[count]
            for incident in resolved_incidents.filter(created__range=(begin, end)):
                local_list.append(incident)
            for maintenance in resolved_maintenances.filter(created__range=(begin, end)):
                local_list.append(maintenance)

            resolved_incidents_maintenances.append((date_begin[count], local_list))

        components = Component.objects.all()
        degraded_components = list(filter(lambda c: c.status == ComponentStatusChoices.DEGRADED_PERFORMANCE, components))
        partial_components = list(filter(lambda c: c.status == ComponentStatusChoices.PARTIAL_OUTAGE, components))
        major_components = list(filter(lambda c: c.status == ComponentStatusChoices.MAJOR_OUTAGE, components))
        maintenance_components = list(filter(lambda c: c.status == ComponentStatusChoices.MAINTENANCE, components))

        if len(maintenance_components) > 0:
            status = ('bg-blue-200', 'text-blue-800', 'mdi-wrench text-blue-500', _('Some systems are undergoing '
                                                                                    'maintenance'))
        elif len(major_components) > 0:
            status = ('bg-red-200', 'text-red-800', 'mdi-alert-circle text-red-500', _('There is a major system outage'))
        elif len(partial_components) > 0:
            status = ('bg-orange-200', 'text-orange-800', 'mdi-alert-circle text-orange-500', _('There is a partial '
                                                                                                'system outage'))
        elif len(degraded_components) > 0:
            status = ('bg-yellow-200', 'text-yellow-800', 'mdi-alert-circle text-yellow-500', _('Some systems are '
                                                                                                'having perfomance '
                                                                                                'issues'))
        else:
            status = ('bg-green-200', 'text-green-800', 'mdi-check-circle text-green-500', _('All systems operational'))

        componentgroups_components = list(chain(component_groups, ungrouped_components))

        metrics = Metric.objects.filter(visibility=True)

        should_show_history = True
        incident_sum = sum(list(map(lambda x: len(x[1]), resolved_incidents_maintenances)))
        if incident_sum == 0 and config.HIDE_HISTORY_WHEN_EMPTY:
            should_show_history = False

        return render(request, self.template_name, {
            'component_groups': component_groups,
            'ungrouped_components': ungrouped_components,
            'status': status,
            'open_incidents_maintenances': open_incidents_maintenances,
            'componentgroups_components': componentgroups_components,
            'metrics': metrics,
            'upcoming_maintenances': upcoming_maintenances,
            'resolved_incidents_maintenances': resolved_incidents_maintenances,
            'should_show_history': should_show_history,
        })

status-page/statuspage/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}Home{% endblock %} | Status-Page</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">

		<link rel="icon" type="image/png" href="{% static 'logo_icon.ico' %}" />

    <link rel="stylesheet" href="{% static 'statuspage-tailwind.css'%}?v={{ settings.VERSION }}" />
    <link rel="stylesheet" href="{% static 'statuspage-external.css'%}?v={{ settings.VERSION }}" />
    <link rel="stylesheet" href="{% static 'statuspage.css'%}?v={{ settings.VERSION }}" />
    <link rel="stylesheet" href="{% static 'statuspage-ss-select-styles.css'%}?v={{ settings.VERSION }}" />

		<script defer src="{% static 'statuspage-alpine.js' %}?v={{ settings.VERSION }}"></script>
		<script src="{% static 'statuspage.js' %}?v={{ settings.VERSION }}"></script>

		<script>
			window.CSRF_TOKEN = "{{ csrf_token }}";
		</script>

		{% block head %}{% endblock %}
	</head>

	<body class="dark">
    {# User messages #}
    {% include 'inc/messages.html' %}

		{% block body %}{% endblock %}
	</body>
</html>

status-page/statuspage/templates/base/base_email.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">

		{% block head %}{% endblock %}
	</head>

	<body>
		{% block body %}{% endblock %}
	</body>
</html>

status-page/statuspage/templates/base/dashboard.html
{% extends 'base/layout.html' %}
{% load utils %}
{% load navigation %}
{% load static %}
{% load helpers %}

{% block content %}
  <div class="min-h-screen flex flex-col">
    <nav class="bg-indigo-600" x-data="{
        open: false,
        close(focusAfter) {
          if (! this.open) return;
          this.open = false;
          focusAfter && focusAfter.focus()
        },
      }"
    >
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <img class="" src="{% static 'logo.svg' %}" alt="Status-Page">
            </div>
            <div class="hidden md:block">
              <div class="ml-10 flex items-baseline space-x-2">
                {% nav %}
              </div>
            </div>
          </div>
          <div class="hidden md:block">
            <div class="ml-4 flex items-center md:ml-6">
              <div class="ml-3">
                <div>
                  <button class="color-mode-toggle text-white"><i class="color-mode-icon mdi"></i></button>
                </div>
              </div>
              <!-- Profile dropdown -->
              <div class="relative ml-3">
                <div>
                  <button @click="open = !open"
                          x-ref="profile_dropdown_button"
                          type="button"
                          class="flex max-w-xs items-center rounded-full bg-indigo-600 text-sm text-white focus:outline-none"
                          id="user-menu-button"
                          aria-expanded="false"
                          aria-haspopup="true"
                  >
                    <span class="sr-only">Open user menu</span>
                    <svg class="h-8 w-8 rounded-full" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                  </button>
                </div>
                <div x-show="open"
                     x-transition:enter="transition ease-out duration-100"
                     x-transition:enter-start="transform opacity-0 scale-95"
                     x-transition:enter-end="transform opacity-100 scale-100"
                     x-transition:leave="transition ease-in duration-75"
                     x-transition:leave-start="transform opacity-100 scale-100"
                     x-transition:leave-end="transform opacity-0 scale-95"
                     x-on:click.outside="close($refs.profile_dropdown_button)"
                     class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
                     role="menu"
                     aria-orientation="vertical"
                     aria-labelledby="user-menu-button"
                     tabindex="-1"
                >
                  <div class="divide-y divide-gray-200">
                    <div class="py-1" role="none">
                      <p class="px-4 py-1 text-gray-500 text-sm">User</p>
                      <a href="{% url 'users:profile' %}" class="{% dashboard_dropdown_active 'users:profile' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">Profile</a>
                      <a href="{% url 'users:preferences' %}" class="{% dashboard_dropdown_active 'users:preferences' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">Preferences</a>
                      <a href="{% url 'users:change_password' %}" class="{% dashboard_dropdown_active 'users:change_password' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">Password</a>
                      <a href="{% url 'users:token_list' %}" class="{% dashboard_dropdown_active 'users:token_list' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">API Tokens</a>
                      <a href="{% url 'users:device_list' %}" class="{% dashboard_dropdown_active 'users:device_list' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">2FA Devices</a>
                    </div>
                    {% if request.user.is_staff %}
                      <div class="py-1" role="none">
                          <a href="{% url 'admin:index' %}" class="{% dashboard_dropdown_active 'admin:index' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">Admin</a>
                      </div>
                    {% endif %}
                    {% if perms.subscribers.view_subscriber and config.SITE_SUBSCRIBERS %}
                      <div class="py-1" role="none">
                          <a href="{% url 'subscribers:subscriber_list' %}" class="{% dashboard_dropdown_active 'subscribers:subscriber_list' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">Subscribers</a>
                      </div>
                    {% endif %}
                    <div class="py-1" role="none">
                      <a href="{% url 'logout' %}" class="{% dashboard_dropdown_active 'logout' %} block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1">Sign out</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="-mr-2 flex md:hidden">
            <!-- Mobile menu button -->
            <button type="button" @click="open = !open" class="inline-flex items-center justify-center rounded-md bg-indigo-600 p-2 text-indigo-200 hover:bg-indigo-500 hover:bg-opacity-75 hover:text-white focus:outline-none" aria-controls="mobile-menu" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg x-show="!open" class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
              <svg x-show="open" class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="md:hidden" id="mobile-menu" x-show="open">
        <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
          {% nav mobile=True %}
        </div>
        <div class="border-t border-indigo-700 pt-4 pb-3">
          <div class="flex items-center px-5">
            <div class="flex-shrink-0">
              <svg class="h-10 w-10 rounded-full" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </div>
          </div>
          <div class="mt-3 space-y-1 px-2">
            <a href="{% url 'users:profile' %}" class="{% dashboard_link_active 'users:profile' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">Profile</a>
            <a href="{% url 'users:preferences' %}" class="{% dashboard_link_active 'users:preferences' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">Preferences</a>
            <a href="{% url 'users:change_password' %}" class="{% dashboard_link_active 'users:change_password' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">Password</a>
            <a href="{% url 'users:token_list' %}" class="{% dashboard_link_active 'users:token_list' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">API Tokens</a>
            <a href="{% url 'users:device_list' %}" class="{% dashboard_link_active 'users:device_list' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">2FA Devices</a>
            {% if request.user.is_staff %}
              <a href="{% url 'admin:index' %}" class="{% dashboard_link_active 'admin:index' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">Admin</a>
            {% endif %}
            {% if perms.extras.view_objectchange %}
              <a href="{% url 'extras:objectchange_list' %}" class="{% dashboard_link_active 'extras:objectchange_list' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">Changelog</a>
            {% endif %}
            <a href="{% url 'logout' %}" class="{% dashboard_link_active 'logout' %} block rounded-md px-3 py-2 text-base font-medium text-white hover:bg-indigo-500 hover:bg-opacity-75">Sign out</a>
          </div>
        </div>
      </div>
    </nav>

    <header class="bg-white shadow">
      <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
        <div class="flex flex-row justify-between items-end">
          <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">{% block title %}{% endblock %}</h1>
          <div class="text-black">{% block controls %}{% endblock %}</div>
        </div>
      </div>
    </header>
    <main class="grow">
      <div class="mx-auto py-4 sm:px-6 lg:px-8 dark:text-white">
        {% if config.BANNER_TOP %}
          <div class="text-center mx-3">
            {{ config.BANNER_TOP|safe }}
          </div>
        {% endif %}

        {% block tabs %}{% endblock %}

        {% block dashboard_content %}{% endblock %}

        {% if config.BANNER_BOTTOM %}
          <div class="text-center mx-3 my-4">
            {{ config.BANNER_BOTTOM|safe }}
          </div>
        {% endif %}
      </div>
    </main>
    <footer class="py-4 px-8 text-gray-500 dark:text-gray-300">
      <div class="flex flex-row justify-between">
        <div class="flex flex-row space-x-2">
          <a type="button" href="{% static 'docs/' %}" target="_blank">
            <div data-tooltip="Docs">
              <i class="mdi mdi-book-open-variant text-blue-300 text-2xl"></i>
            </div>
          </a>

          <a type="button" href="{% url 'api-root' %}" target="_blank">
            <div data-tooltip="REST API">
              <i class="mdi mdi-cloud-braces text-blue-300 text-2xl"></i>
            </div>
          </a>

          <a type="button" href="{% url 'api_docs' %}" target="_blank">
            <div data-tooltip="REST API documentation">
              <i class="mdi mdi-book text-blue-300 text-2xl"></i>
            </div>
          </a>

          <a type="button" href="https://github.com/status-page/status-page" target="_blank">
            <div data-tooltip="Source Code">
              <i class="mdi mdi-github text-blue-300 text-2xl"></i>
            </div>
          </a>
        </div>
        <div class="flex flex-row space-x-4">
          <div>{% annotated_now %} {% now 'T' %}</div>
          <div>{{ settings.HOSTNAME }} (v{{ settings.VERSION }})</div>
        </div>
      </div>
    </footer>
  </div>
{% endblock %}

status-page/statuspage/templates/base/layout.html
{% extends 'base/base.html' %}

{% block body %}
  <div class="min-h-screen bg-zinc-100 dark:bg-zinc-600 dark:text-white">
    {% block content %}{% endblock %}

    {% block modals %}{% endblock %}
  </div>
{% endblock body %}